using Insolvex.Domain.Enums;

namespace Insolvex.Core.DTOs;

public record CaseDto(
    Guid Id,
    string CaseNumber,
    string? CourtName,
    string? CourtSection,
    string? JudgeSyndic,
    string DebtorName,
    string? DebtorCui,
    ProcedureType ProcedureType,
    string Status,
    string? LawReference,
    string? PractitionerName,
    string? PractitionerRole,
    string? PractitionerFiscalId,
    string? PractitionerDecisionNo,
    DateTime? NoticeDate,
    DateTime? OpeningDate,
    DateTime? NextHearingDate,
    DateTime? ClaimsDeadline,
    DateTime? ContestationsDeadline,
    DateTime? DefinitiveTableDate,
    DateTime? ReorganizationPlanDeadline,
    DateTime? ClosureDate,
    DateTime? StatusChangedAt,
    decimal? TotalClaimsRon,
    decimal? SecuredClaimsRon,
    decimal? UnsecuredClaimsRon,
    decimal? BudgetaryClaimsRon,
    decimal? EmployeeClaimsRon,
    decimal? EstimatedAssetValueRon,
    string? BpiPublicationNo,
    DateTime? BpiPublicationDate,
    string? OpeningDecisionNo,
    string? Notes,
    Guid? CompanyId,
    string? CompanyName,
    Guid? AssignedToUserId,
    string? AssignedToName,
    DateTime CreatedOn,
    int DocumentCount,
    int PartyCount
);

public record CreateCaseRequest(
    string CaseNumber,
    string? CourtName,
    string? CourtSection,
    string DebtorName,
    string? DebtorCui,
    ProcedureType? ProcedureType,
    string? LawReference,
    Guid? CompanyId
);

public record UpdateCaseRequest(
    string? CaseNumber,
    string? CourtName,
    string? CourtSection,
    string? JudgeSyndic,
    ProcedureType? ProcedureType,
    string? Status,
    string? LawReference,
    string? PractitionerName,
    string? PractitionerRole,
    string? PractitionerFiscalId,
    string? PractitionerDecisionNo,
    DateTime? NoticeDate,
    DateTime? OpeningDate,
    DateTime? NextHearingDate,
    DateTime? ClaimsDeadline,
    DateTime? ContestationsDeadline,
    DateTime? DefinitiveTableDate,
    DateTime? ReorganizationPlanDeadline,
    DateTime? ClosureDate,
    decimal? TotalClaimsRon,
    decimal? SecuredClaimsRon,
    decimal? UnsecuredClaimsRon,
    decimal? BudgetaryClaimsRon,
    decimal? EmployeeClaimsRon,
    decimal? EstimatedAssetValueRon,
    string? BpiPublicationNo,
    DateTime? BpiPublicationDate,
    string? OpeningDecisionNo,
    string? Notes,
    Guid? CompanyId,
    Guid? AssignedToUserId
);
