using Insolvio.Domain.Enums;

namespace Insolvio.Domain.Entities;

public class CompanyTask : TenantScopedEntity
{
    public Guid CompanyId { get; set; }
    public virtual Company? Company { get; set; }

    /// <summary>Optional link to an insolvency case (null for company-level tasks).</summary>
    public Guid? CaseId { get; set; }
    public virtual InsolvencyCase? Case { get; set; }

    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? Labels { get; set; }

    /// <summary>Task summary text used for quick display.</summary>
    public string? Summary { get; set; }

    /// <summary>
    /// Practitioner-written summary specifically for the mandatory periodic report.
    /// Only tasks with this field populated are included in the periodic report.
    /// </summary>
    public string? ReportSummary { get; set; }

    /// <summary>Language-keyed JSON map of task summaries (e.g. en/ro/hu).</summary>
    public string? SummaryByLanguageJson { get; set; }

    /// <summary>Mandatory deadline per InsolvencyAppRules.</summary>
    public DateTime? Deadline { get; set; }

    /// <summary>Source of the deadline: Notice, CompanyDefault, Manual.</summary>
    public string? DeadlineSource { get; set; }

    /// <summary>Whether this is a critical deadline that triggers escalation.</summary>
    public bool IsCriticalDeadline { get; set; }

    /// <summary>Category: Document, Email, Filing, Meeting, Call, Review, Payment, Report, Compliance.</summary>
    public string? Category { get; set; }

    public Enums.TaskStatus Status { get; set; } = Enums.TaskStatus.Open;

    /// <summary>Reason for blocking this task (required when status is Blocked).</summary>
    public string? BlockReason { get; set; }

    /// <summary>Default assignee = uploader unless workflow says otherwise.</summary>
    public Guid? AssignedToUserId { get; set; }
    public virtual User? AssignedTo { get; set; }

    /// <summary>Who created this task.</summary>
    public Guid? CreatedByUserId { get; set; }

    /// <summary>JSON array of task IDs that must complete before this task can start.</summary>
    public string? DependenciesJson { get; set; }

    /// <summary>Escalation policy ID reference (configurable per tenant).</summary>
    public string? EscalationPolicyId { get; set; }

    /// <summary>Reminder schedule ID reference.</summary>
    public string? ReminderScheduleId { get; set; }

    /// <summary>JSON array of related party IDs.</summary>
    public string? RelatedPartyIdsJson { get; set; }

    /// <summary>JSON array of related document IDs.</summary>
    public string? RelatedDocumentIdsJson { get; set; }

    /// <summary>Related email ID (for email send tasks).</summary>
    public Guid? RelatedEmailId { get; set; }

    /// <summary>Date/time the task was completed.</summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// True = ad-hoc task created manually by a user; not tied to a workflow stage.
    /// False (default) = task generated by the workflow engine.
    /// </summary>
    public bool IsAdHoc { get; set; } = false;

    /// <summary>
    /// If set, this task was generated for a specific CaseWorkflowStage.
    /// Null for ad-hoc tasks and company-level tasks.
    /// </summary>
    public Guid? WorkflowStageId { get; set; }
    public virtual CaseWorkflowStage? WorkflowStage { get; set; }

    // Navigation
    /// <summary>Notes / activity log entries for this task.</summary>
    public virtual ICollection<TaskNote> Notes { get; set; } = new List<TaskNote>();

    /// <summary>Additional (secondary) assignees beyond the primary AssignedToUserId.</summary>
    public virtual ICollection<TaskAssignee> Assignees { get; set; } = new List<TaskAssignee>();
}
